logging:
  level: INFO
  loggers:
    io.tokern: ${BASTION_LOG_LEVEL:-INFO}
server:
  rootPath: /api
  applicationConnectors:
    - type: http
      port: 3145
  adminConnectors:
    - type: http
      port: 3146

database:
  # the name of your JDBC driver
  driverClass: org.postgresql.Driver
  user: ${BASTION_USER:-}
  password: ${BASTION_PWD:-}
  url: ${BASTION_JDBC_URL:-}

flyway:
  schemas:
    - ${BASTION_SCHEMA:-}
