logging:
  level: INFO
  loggers:
    io.tokern: ${DBAUDIT_LOG_LEVEL:-INFO}
server:
  rootPath: /api
  applicationConnectors:
    - type: http
      port: 3145
  adminConnectors:
    - type: http
      port: 3146

database:
  # the name of your JDBC driver
  driverClass: org.postgresql.Driver
  user: ${DBAUDIT_USER:-}
  password: ${DBAUDIT_PWD:-}
  url: ${DBAUDIT_JDBC_URL:-}

encryptionSecret: ${DBAUDIT_ENCRYPTION_PASSWORD:-}

flyway:
  schemas:
    - ${DBAUDIT_SCHEMA:-}
