version: '3'
services:
  dbaudit:
    image: tokern/dbaudit:latest
    ports:
      - "3145:3145"
      - "3146:3146"
    environment:
      DBAUDIT_USER: dbaudit_user
      DBAUDIT_PWD: passw0rd
      DBAUDIT_DB: dbauditdb
      DBAUDIT_SCHEMA: app
      POSTGRESQL_HOSTNAME: postgres
  postgres:
    image: "postgres:12.1-alpine"
    environment:
      POSTGRES_USER: dbaudit_user
      POSTGRES_PASSWORD: passw0rd
      POSTGRES_DB: dbauditdb

